/*
 Navicat PostgreSQL Data Transfer

 Source Server         : dwx
 Source Server Type    : PostgreSQL
 Source Server Version : 100004
 Source Host           : 172.19.153.61:5432
 Source Catalog        : postgres
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 100004
 File Encoding         : 65001

 Date: 08/03/2019 22:19:22
*/


-- ----------------------------
-- Sequence structure for goods_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."goods_id_seq";
CREATE SEQUENCE "public"."goods_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for supplier_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."supplier_id_seq";
CREATE SEQUENCE "public"."supplier_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for employee
-- ----------------------------
DROP TABLE IF EXISTS "public"."employee";
CREATE TABLE "public"."employee" (
  "id" int4 NOT NULL,
  "name" varchar(40) COLLATE "pg_catalog"."default" NOT NULL,
  "age" int2 NOT NULL,
  "sex" int2 NOT NULL,
  "position" varchar(8) COLLATE "pg_catalog"."default" NOT NULL,
  "salary" float8 NOT NULL,
  " contact" varchar(40) COLLATE "pg_catalog"."default" NOT NULL,
  "site" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "entrytime" timestamp(0) NOT NULL
)
;

-- ----------------------------
-- Table structure for export
-- ----------------------------
DROP TABLE IF EXISTS "public"."export";
CREATE TABLE "public"."export" (
  "id" int4 NOT NULL,
  "gid" int4,
  "num" int4,
  "timestamp" timestamp(6)
)
;

-- ----------------------------
-- Table structure for goods
-- ----------------------------
DROP TABLE IF EXISTS "public"."goods";
CREATE TABLE "public"."goods" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "name" varchar(60) COLLATE "pg_catalog"."default",
  "num" int4,
  "im_price" numeric(10,2),
  "barcode_id" int4,
  "discount" numeric(2,2),
  "sup_id" int4
)
;

-- ----------------------------
-- Table structure for import
-- ----------------------------
DROP TABLE IF EXISTS "public"."import";
CREATE TABLE "public"."import" (
  "id" int4 NOT NULL,
  "num" int4,
  "gid" int4,
  "timestamp" timestamp(6)
)
;

-- ----------------------------
-- Table structure for sales
-- ----------------------------
DROP TABLE IF EXISTS "public"."sales";
CREATE TABLE "public"."sales" (
  "id" int4 NOT NULL,
  "gid" int4,
  "num" int4,
  "im_price" numeric(10,2),
  "src_price" numeric(10,2),
  "sale_price" numeric(10,2),
  "discount" numeric(2,2),
  "time" timestamp(6),
  "paid_money" numeric(10,2)
)
;

-- ----------------------------
-- Table structure for supplier
-- ----------------------------
DROP TABLE IF EXISTS "public"."supplier";
CREATE TABLE "public"."supplier" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "name" varchar(60) COLLATE "pg_catalog"."default",
  "contact" varchar(60) COLLATE "pg_catalog"."default" NOT NULL,
  "address" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for warehouse
-- ----------------------------
DROP TABLE IF EXISTS "public"."warehouse";
CREATE TABLE "public"."warehouse" (
  "id" int4 NOT NULL,
  "gid" int4 NOT NULL,
  "num" int4 NOT NULL
)
;

-- ----------------------------
-- Function structure for auditlogfunc
-- ----------------------------
DROP FUNCTION IF EXISTS "public"."auditlogfunc"();
CREATE OR REPLACE FUNCTION "public"."auditlogfunc"()
  RETURNS "pg_catalog"."trigger" AS $BODY$  
    BEGIN  
        INSERT INTO  conmmodity("Cno") 
        VALUES (new.cno);  
        RETURN NEW;   
    END;  
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."goods_id_seq"
OWNED BY "public"."goods"."id";
SELECT setval('"public"."goods_id_seq"', 7, true);
ALTER SEQUENCE "public"."supplier_id_seq"
OWNED BY "public"."supplier"."id";
SELECT setval('"public"."supplier_id_seq"', 7, true);

-- ----------------------------
-- Primary Key structure for table employee
-- ----------------------------
ALTER TABLE "public"."employee" ADD CONSTRAINT "employee_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table export
-- ----------------------------
ALTER TABLE "public"."export" ADD CONSTRAINT "export_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table goods
-- ----------------------------
ALTER TABLE "public"."goods" ADD CONSTRAINT "goods_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Triggers structure for table import
-- ----------------------------
CREATE TRIGGER "nihai" AFTER INSERT ON "public"."import"
FOR EACH ROW
EXECUTE PROCEDURE "public"."auditlogfunc"();

-- ----------------------------
-- Primary Key structure for table import
-- ----------------------------
ALTER TABLE "public"."import" ADD CONSTRAINT "import_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table sales
-- ----------------------------
ALTER TABLE "public"."sales" ADD CONSTRAINT "sales_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table supplier
-- ----------------------------
ALTER TABLE "public"."supplier" ADD CONSTRAINT "Supplier_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table warehouse
-- ----------------------------
ALTER TABLE "public"."warehouse" ADD CONSTRAINT "warehouse_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table export
-- ----------------------------
ALTER TABLE "public"."export" ADD CONSTRAINT "goods" FOREIGN KEY ("gid") REFERENCES "public"."goods" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table goods
-- ----------------------------
ALTER TABLE "public"."goods" ADD CONSTRAINT "supplier" FOREIGN KEY ("sup_id") REFERENCES "public"."supplier" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table import
-- ----------------------------
ALTER TABLE "public"."import" ADD CONSTRAINT "goods" FOREIGN KEY ("gid") REFERENCES "public"."goods" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ----------------------------
-- Foreign Keys structure for table sales
-- ----------------------------
ALTER TABLE "public"."sales" ADD CONSTRAINT "goods" FOREIGN KEY ("gid") REFERENCES "public"."goods" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
